name: build

# Add a button to trigger the workflow
on: 
  repository_dispatch:
  workflow_dispatch:

env:
  libressl_version: 3.8.0
  nginx_version: 1.25.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone Nginx WebDAV
      env: 
        REPO_URL: https://github.com/arut/nginx-dav-ext-module
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH

    - name: Clone Nginx Brotli
      env: 
        REPO_URL: https://github.com/google/ngx_brotli
        REPO_BRANCH: master
      run: |
        git clone --depth 1 --recursive $REPO_URL -b $REPO_BRANCH
        
    - name: Download libressl
      run: |
        wget https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${{env.libressl_version}}.tar.gz -O libressl.tar.gz

    - name: Download Nginx
      run: |
        wget https://nginx.org/download/nginx-${{env.nginx_version}}.tar.gz -O nginx.tar.gz

    - name: Docker Build Nginx
      run: |
        ls -la
        sudo docker build --no-cache -t wangyu.live:16000/dayu-nginx --build-arg NGINX_VERSION=${{env.nginx_version}} --build-arg LIBRESSL_VERSION=${{env.libressl_version}} .

    - name : Docker Pack Nginx
      run: |
        sudo docker save wangyu.live:16000/dayu-nginx -o dayu-nginx.tar

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: dayu-nginx
        path: dayu-nginx.tar
