name: build

# Add a button to trigger the workflow
on: 
  repository_dispatch:
  workflow_dispatch:

env:
  libressl_version: 3.8.2
  nginx_version: 1.25.3
  ngx_brotli_commit: 6e975bcb015f62e1f303054897783355e2a877dc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone Nginx WebDAV
      env: 
        REPO_URL: https://github.com/arut/nginx-dav-ext-module
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH

    - name: Clone Nginx Headers More
      env: 
        REPO_URL: https://github.com/openresty/headers-more-nginx-module
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH

    - name: Clone Nginx Brotli
      env: 
        REPO_URL: https://github.com/google/ngx_brotli
        REPO_BRANCH: master
      run: |
        mkdir -p ngx_brotli
        cd ngx_brotli
        git init
        git remote add origin $REPO_URL
        git fetch --depth 1 origin ${{env.ngx_brotli_commit}}
        git checkout --recurse-submodules -q FETCH_HEAD
        git submodule update --init --depth 1
        
    - name: Download libressl
      run: |
        wget https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${{env.libressl_version}}.tar.gz -O libressl.tar.gz

    - name: Download Nginx
      run: |
        wget https://nginx.org/download/nginx-${{env.nginx_version}}.tar.gz -O nginx.tar.gz

    - name: Docker Build Nginx
      run: |
        sudo docker build --no-cache -t wangyu.live:16000/dayu-nginx --build-arg NGINX_VERSION=${{env.nginx_version}} --build-arg LIBRESSL_VERSION=${{env.libressl_version}} .

    - name : Docker Pack Nginx
      run: |
        sudo docker save wangyu.live:16000/dayu-nginx -o dayu-nginx.tar
        sudo chmod 777 dayu-nginx.tar

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: dayu-nginx
        path: dayu-nginx.tar
